### PR TITLE
Created dockerfile for setup

### PR DESCRIPTION
**Pull request by Kd-Here**
Hey @Trevato can you please review it?
I know it is not complted but need your help that's why open PR.
Could you please help me with token.txt file how should that add in image.

### CODE REVIEW

**Comment by Trevato** [comment]
You can pass the token as an environment variable. I had the token.txt there because it helped when debugging.

**Comment by Trevato** [comment]
@Kd-Here I created a [commit](https://github.com/Trevato/soundboard/commit/adf88e5422caa3188c83bcbeb8547c45834ef070) with my attempt at the Dockerfile for reference.

**Comment by Kd-Here** [comment]
Thanks for your commit! 
I am currently running code on my pc but got this error.


        Missing Discord bot's API token.
        Please add the TOKEN environment variable.
        For more info: https://www.writebots.com/discord-bot-token/
I followed article and created token txt but still got error.

**Comment by Trevato** [comment]
@Kd-Here When trying to use this commit, you must run it with `docker run`. If you'd like to use the `token.txt` method, you must switch to the main branch then run with `python main.py`. It should work then.

**Pull request closed without merging**
